export interface AllaName {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
}

export const ALLAH_NAMES: AllaName[] = [
  { id: 1, arabic: "اللَّهُ", transliteration: "Allah", meaning: "The Greatest Name" },
  { id: 2, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Most Gracious" },
  { id: 3, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", meaning: "The Most Merciful" },
  { id: 4, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "The King, The Sovereign" },
  { id: 5, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy" },
  { id: 6, arabic: "السَّلاَمُ", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { id: 7, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Granter of Security" },
  { id: 8, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Protector" },
  { id: 9, arabic: "الْعَزِيزُ", transliteration: "Al-'Aziz", meaning: "The Mighty" },
  { id: 10, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller" },
  { id: 11, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Majestic" },
  { id: 12, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { id: 13, arabic: "الْبَارِئُ", transliteration: "Al-Bari'", meaning: "The Originator" },
  { id: 14, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { id: 15, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Forgiving" },
  { id: 16, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer" },
  { id: 17, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { id: 18, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider" },
  { id: 19, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { id: 20, arabic: "الْعَلِيمُ", transliteration: "Al-'Alim", meaning: "The All-Knowing" },
  { id: 21, arabic: "الْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Withholder" },
  { id: 22, arabic: "الْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Extender" },
  { id: 23, arabic: "الْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Humiliator" },
  { id: 24, arabic: "الرَّافِعُ", transliteration: "Ar-Rafi'", meaning: "The Exalter" },
  { id: 25, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Bestower of Honour" },
  { id: 26, arabic: "الْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Dishonorer" },
  { id: 27, arabic: "السَّمِيعُ", transliteration: "As-Sami'", meaning: "The All-Hearing" },
  { id: 28, arabic: "الْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { id: 29, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge" },
  { id: 30, arabic: "الْعَدْلُ", transliteration: "Al-'Adl", meaning: "The Just" },
  { id: 31, arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle One" },
  { id: 32, arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware" },
  { id: 33, arabic: "الْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing" },
  { id: 34, arabic: "الْعَظِيمُ", transliteration: "Al-'Azim", meaning: "The Magnificent" },
  { id: 35, arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The Forgiving" },
  { id: 36, arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative" },
  { id: 37, arabic: "الْعَلِيُّ", transliteration: "Al-'Ali", meaning: "The Most High" },
  { id: 38, arabic: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Most Great" },
  { id: 39, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver" },
  { id: 40, arabic: "الْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Nourisher" },
  { id: 41, arabic: "الْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner" },
  { id: 42, arabic: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Sublime" },
  { id: 43, arabic: "الْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous" },
  { id: 44, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful" },
  { id: 45, arabic: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive" },
  { id: 46, arabic: "الْوَاسِعُ", transliteration: "Al-Wasi'", meaning: "The All-Encompassing" },
  { id: 47, arabic: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The All-Wise" },
  { id: 48, arabic: "الْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving" },
  { id: 49, arabic: "الْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious" },
  { id: 50, arabic: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector" },
  { id: 51, arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness" },
  { id: 52, arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { id: 53, arabic: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee" },
  { id: 54, arabic: "الْقَوِيُّ", transliteration: "Al-Qawi", meaning: "The Strong" },
  { id: 55, arabic: "الْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm" },
  { id: 56, arabic: "الْوَلِيُّ", transliteration: "Al-Wali", meaning: "The Protecting Friend" },
  { id: 57, arabic: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy" },
  { id: 58, arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The Reckoner" },
  { id: 59, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi'", meaning: "The Originator" },
  { id: 60, arabic: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer" },
  { id: 61, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { id: 62, arabic: "الْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Taker of Life" },
  { id: 63, arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { id: 64, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Subsisting" },
  { id: 65, arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Finder" },
  { id: 66, arabic: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Noble" },
  { id: 67, arabic: "الْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The One" },
  { id: 68, arabic: "الأَحَدُ", transliteration: "Al-Ahad", meaning: "The Unique" },
  { id: 69, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal" },
  { id: 70, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The All-Powerful" },
  { id: 71, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Powerful" },
  { id: 72, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter" },
  { id: 73, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { id: 74, arabic: "الأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { id: 75, arabic: "الآخِرُ", transliteration: "Al-Akhir", meaning: "The Last" },
  { id: 76, arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest" },
  { id: 77, arabic: "الْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden" },
  { id: 78, arabic: "الْوَالِي", transliteration: "Al-Wali", meaning: "The Governor" },
  { id: 79, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted" },
  { id: 80, arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness" },
  { id: 81, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Ever-Accepting of Repentance" },
  { id: 82, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { id: 83, arabic: "الْعَفُوُّ", transliteration: "Al-'Afuw", meaning: "The Pardoner" },
  { id: 84, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Compassionate" },
  { id: 85, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Maliku'l-Mulk", meaning: "Owner of All Sovereignty" },
  { id: 86, arabic: "ذُو الْجَلاَلِ وَالإِكْرَامِ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty and Bounty" },
  { id: 87, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { id: 88, arabic: "الْجَامِعُ", transliteration: "Al-Jami'", meaning: "The Gatherer" },
  { id: 89, arabic: "الْغَنِيُّ", transliteration: "Al-Ghani", meaning: "The Self-Sufficient" },
  { id: 90, arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { id: 91, arabic: "الْمَانِعُ", transliteration: "Al-Mani'", meaning: "The Preventer" },
  { id: 92, arabic: "الضَّارُّ", transliteration: "Ad-Darr", meaning: "The Distresser" },
  { id: 93, arabic: "النَّافِعُ", transliteration: "An-Nafi'", meaning: "The Benefiter" },
  { id: 94, arabic: "النُّورُ", transliteration: "An-Nur", meaning: "The Light" },
  { id: 95, arabic: "الْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { id: 96, arabic: "الْبَدِيعُ", transliteration: "Al-Badi'", meaning: "The Incomparable Originator" },
  { id: 97, arabic: "الْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting" },
  { id: 98, arabic: "الْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor" },
  { id: 99, arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path" },
];
